CREATE TABLE payments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_ref   VARCHAR(64)   NOT NULL,
    booking_reference VARCHAR(64)   NOT NULL,
    booking_id        BIGINT        NOT NULL,
    amount            NUMERIC(12,2) NOT NULL,
    status            VARCHAR(30)   NOT NULL,
    failure_reason    VARCHAR(255),
    created_at        TIMESTAMPTZ   NOT NULL,
    updated_at        TIMESTAMPTZ   NOT NULL,
    version           BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_payment_transaction_ref   UNIQUE (transaction_ref),
    CONSTRAINT uq_payment_booking_reference UNIQUE (booking_reference)
);

CREATE INDEX idx_payments_booking_reference ON payments (booking_reference);
