CREATE TABLE bookings (
                          id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          booking_reference VARCHAR(64)    NOT NULL,
                          user_id           BIGINT         NOT NULL,
                          event_id          BIGINT         NOT NULL,
                          status            VARCHAR(30)    NOT NULL,
                          total_amount      NUMERIC(12, 2) NOT NULL,
                          failure_reason    VARCHAR(255),
                          created_at        TIMESTAMPTZ    NOT NULL,
                          updated_at        TIMESTAMPTZ    NOT NULL,
                          version           BIGINT         NOT NULL DEFAULT 0,
                          CONSTRAINT uq_booking_reference UNIQUE (booking_reference)
);

CREATE INDEX idx_bookings_user_id ON bookings (user_id);
CREATE INDEX idx_bookings_status  ON bookings (status);

CREATE TABLE booking_seats (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               booking_id  BIGINT         NOT NULL,
                               seat_id     BIGINT         NOT NULL,
                               seat_number VARCHAR(50)    NOT NULL,
                               price       NUMERIC(10, 2) NOT NULL,
                               created_at  TIMESTAMPTZ    NOT NULL,
                               updated_at  TIMESTAMPTZ    NOT NULL,
                               version     BIGINT         NOT NULL DEFAULT 0,
                               CONSTRAINT fk_booking_seats_booking
                                   FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
                               CONSTRAINT uq_booking_seat UNIQUE (booking_id, seat_id)
);

CREATE INDEX idx_booking_seats_booking_id ON booking_seats (booking_id);