CREATE TABLE events (
                        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name           VARCHAR(255) NOT NULL,
                        description    TEXT,
                        venue          VARCHAR(255) NOT NULL,
                        starts_at      TIMESTAMPTZ  NOT NULL,
                        total_capacity INTEGER      NOT NULL,
                        created_at     TIMESTAMPTZ  NOT NULL,
                        updated_at     TIMESTAMPTZ  NOT NULL,
                        version        BIGINT       NOT NULL DEFAULT 0
);