CREATE TABLE notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type        VARCHAR(40)  NOT NULL,
    booking_reference VARCHAR(64)  NOT NULL,
    message           VARCHAR(500) NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_notification_event UNIQUE (event_type, booking_reference)
);

CREATE INDEX idx_notifications_booking_reference ON notifications (booking_reference);
