CREATE TABLE seats (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       event_id    BIGINT       NOT NULL,
                       seat_number VARCHAR(50)  NOT NULL,
                       status      VARCHAR(20)  NOT NULL,
                       created_at  TIMESTAMPTZ  NOT NULL,
                       updated_at  TIMESTAMPTZ  NOT NULL,
                       version     BIGINT       NOT NULL DEFAULT 0,
                       CONSTRAINT uq_seat_per_event UNIQUE (event_id, seat_number)
);

CREATE INDEX idx_seats_event_id ON seats (event_id);