server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/api/events/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway